apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: dheerajkr7866/3-tier-app-service-b:2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: my-namespace
spec:
  ports:
  - port: 80              # Expose the service on port 80 for Ingress
    targetPort: 5000       # Redirect to the container's 5000 port
  selector:
    app: service-b
  type: ClusterIP          # Use ClusterIP to work with Ingress
